name: Inject Secret into Existing HTML
permissions:
  contents: write

on: [push]

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Secure Debugging (Mask Secret)
        env:
          MY_SECRET: ${{ secrets.APIKEY }}
        run: |
          echo "::add-mask::$MY_SECRET"  
          echo "✅ Secret is set but hidden in logs!"

      - name: Replace Placeholder with Secret
        env:
          MY_SECRET: ${{ secrets.APIKEY }}
        run: |
          ESCAPED_SECRET=$(printf '%s\n' "$MY_SECRET" | sed 's/[&/\]/\\&/g')
          sed -i "s|<!-- SECRET_PLACEHOLDER -->|$ESCAPED_SECRET|g" index.html

      - name: Check If Secret Was Replaced (Without Leaking)
        run: |
          if grep -q "SECRET_PLACEHOLDER" index.html; then
            echo "❌ Secret was NOT replaced!";
            exit 1;
          else
            echo "✅ Secret replaced successfully (Value is hidden)";
          fi

      - name: Commit Updated HTML
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html
          git diff --cached --quiet || git commit -m "Injected secret into index.html"
          git push
